# Generated by Django 4.1.4 on 2023-07-29 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0002_satellites_delete_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Satellites',
            new_name='Satellite',
        ),
    ]
