# Generated by Django 4.1.4 on 2023-07-29 06:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0004_remove_satellite_id_remove_satellite_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='launch_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 12, 20, 34, 132205), verbose_name='Launch Date'),
        ),
    ]
