# Generated by Django 4.1.4 on 2023-07-29 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0006_alter_satellite_launch_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='launch_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 13, 12, 5, 431221), verbose_name='Launch Date'),
        ),
    ]
