# Generated by Django 4.1.4 on 2023-07-29 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0009_satellite_last_tle_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='tle',
            field=models.TextField(default='', editable=False, verbose_name='Satellite Tle'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='description',
            field=models.TextField(default='', verbose_name='About Satellite'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='last_tle_update',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 14, 30, 48, 264056), editable=False, verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='launch_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 14, 30, 48, 264056), verbose_name='Launch Date'),
        ),
    ]
