# Generated by Django 4.1.4 on 2023-07-29 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0011_alter_satellite_last_tle_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Sensor Name')),
                ('resolution_type', models.CharField(default=None, max_length=30, verbose_name='Resolution Type')),
                ('resolution_value', models.FloatField(default=None, verbose_name='Resolution [m]')),
                ('swath', models.FloatField(default=None, verbose_name='Swath [km]')),
            ],
        ),
        migrations.AddField(
            model_name='satellite',
            name='orbit',
            field=models.CharField(default='', max_length=20, verbose_name='Orbit Type'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='status',
            field=models.CharField(choices=[('IN ORBIT', 'IN ORBIT'), ('NOT TRACKED', 'NOT TRACKED')], default='IN ORBIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='last_tle_update',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 21, 57, 33, 380086), editable=False, verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='launch_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 21, 57, 33, 380086), verbose_name='Launch Date'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='sensors',
            field=models.ManyToManyField(to='satTrack.sensors'),
        ),
    ]
