# Generated by Django 4.1.4 on 2023-07-29 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0013_satellite_swath_alter_satellite_last_tle_update_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sensors',
            new_name='Sensor',
        ),
        migrations.AddField(
            model_name='satellite',
            name='application',
            field=models.TextField(default=None, verbose_name='Applications'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='tilt_type',
            field=models.CharField(choices=[('ROLL', 'ROLL'), ('YAW', 'YAW'), ('PITCH', 'PITCH')], default='ROLL', max_length=20, verbose_name='Tilt type'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='tilt_value',
            field=models.FloatField(default=None, verbose_name='Tilt value'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='last_tle_update',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 22, 25, 4, 27041), editable=False, verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='launch_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 22, 25, 4, 27041), verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='status',
            field=models.CharField(choices=[('IN ORBIT', 'IN ORBIT'), ('NOT TRACKED', 'NOT TRACKED')], default='IN ORBIT', max_length=20, verbose_name='Status'),
        ),
    ]
