# Generated by Django 4.1.4 on 2023-07-29 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0016_alter_satellite_application_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellite',
            name='application',
        ),
        migrations.AlterField(
            model_name='satellite',
            name='last_tle_update',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 22, 27, 25, 576142), editable=False, verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='launch_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 22, 27, 25, 576142), verbose_name='Launch Date'),
        ),
    ]
