# Generated by Django 4.1.4 on 2023-07-29 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0020_remove_satellite_tilt_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellite',
            name='orbit',
        ),
        migrations.AlterField(
            model_name='satellite',
            name='last_tle_update',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 22, 32, 3, 217217), editable=False, verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='launch_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 22, 32, 3, 217217), verbose_name='Launch Date'),
        ),
    ]
