# Generated by Django 4.1.4 on 2023-07-29 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0023_rename_sensors_sensor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='application',
            field=models.TextField(default='s', verbose_name='Application'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='satellite',
            name='orbit',
            field=models.CharField(default='', max_length=20, verbose_name='Orbit Type'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='tilt_type',
            field=models.CharField(choices=[('ROLL', 'ROLL'), ('YAW', 'YAW'), ('PITCH', 'PITCH')], default='ROLL', max_length=20, verbose_name='Tilt type'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='tilt_value',
            field=models.FloatField(default='', verbose_name='Tilt value'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='last_tle_update',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 22, 41, 58, 155168), editable=False, verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='launch_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 22, 41, 58, 155168), verbose_name='Launch Date'),
        ),
    ]
