# Generated by Django 4.1.4 on 2023-07-29 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0025_alter_satellite_last_tle_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='application',
            field=models.TextField(default=None, verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='last_tle_update',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 22, 42, 52, 441667), editable=False, verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='launch_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 22, 42, 52, 441667), verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='tilt_value',
            field=models.FloatField(default=0, verbose_name='Tilt value'),
        ),
    ]
