# Generated by Django 4.1.4 on 2023-07-29 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0032_remove_satellite_application_remove_satellite_orbit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='tilt_value',
            field=models.TextField(default='', verbose_name='Tilt value'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='last_tle_update',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 22, 49, 28, 85049), editable=False, verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='launch_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 22, 49, 28, 85049), verbose_name='Launch Date'),
        ),
    ]
