# Generated by Django 4.1.4 on 2023-07-30 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0037_alter_satellite_last_tle_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='apogee',
            field=models.FloatField(default=0, verbose_name='Apogee'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='inclination',
            field=models.FloatField(default=0, verbose_name='Inclination [°]'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='manufacturer',
            field=models.CharField(default='', max_length=15, verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='orbital_period',
            field=models.FloatField(default=0, verbose_name='Orbital Period [m]'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='perigee',
            field=models.FloatField(default=0, verbose_name='Perigee'),
        ),
        migrations.AddField(
            model_name='satellite',
            name='satellite_type',
            field=models.CharField(default='', max_length=30, verbose_name='Satellite type'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='negative_tilting',
            field=models.FloatField(default=0, verbose_name='Negative Tilting'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='positive_tilting',
            field=models.FloatField(default=0, verbose_name='Positive Tilting'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='tilting_type',
            field=models.CharField(default='', max_length=20, verbose_name='Tilting Type'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='last_tle_update',
            field=models.DateField(default=datetime.datetime(2023, 7, 30, 10, 10, 58, 246253), editable=False, verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='launch_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 30, 10, 10, 58, 246253), verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('NOT TRACKED', 'not_tracked')], default='IN ORBIT', max_length=20, verbose_name='Status'),
        ),
    ]
