# Generated by Django 4.1.4 on 2023-07-30 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0038_satellite_apogee_satellite_inclination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellite',
            name='tilt_type',
        ),
        migrations.RemoveField(
            model_name='satellite',
            name='tilt_value',
        ),
        migrations.AlterField(
            model_name='satellite',
            name='last_tle_update',
            field=models.DateField(default=datetime.datetime(2023, 7, 30, 10, 12, 14, 771207), editable=False, verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='launch_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 30, 10, 12, 14, 771207), verbose_name='Launch Date'),
        ),
    ]
