# Generated by Django 4.1.4 on 2023-07-30 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0039_remove_satellite_tilt_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='id',
        ),
        migrations.AlterField(
            model_name='satellite',
            name='last_tle_update',
            field=models.DateField(default=datetime.datetime(2023, 7, 30, 18, 49, 11, 946807), editable=False, verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='launch_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 30, 18, 49, 11, 946807), verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('not_tracked', 'NOT TRACKED')], default='IN ORBIT', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Sensor Name'),
        ),
    ]
