# Generated by Django 4.1.4 on 2023-07-30 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0044_remove_sensor_id_alter_satellite_last_tle_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='satellite',
            name='last_tle_update',
            field=models.DateField(default=datetime.datetime(2023, 7, 30, 18, 59, 45, 48649), editable=False, verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='launch_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 30, 18, 59, 45, 48649), verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Sensor Name'),
        ),
    ]
