# Generated by Django 4.1.4 on 2023-07-29 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0008_alter_satellite_launch_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='last_tle_update',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 14, 26, 33, 21914), verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='launch_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 14, 26, 33, 21914), verbose_name='Launch Date'),
        ),
    ]
