# Generated by Django 4.1.4 on 2023-07-29 16:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satTrack', '0017_remove_satellite_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='last_tle_update',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 22, 29, 11, 563162), editable=False, verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='launch_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 29, 22, 29, 11, 563162), verbose_name='Launch Date'),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='tilt_value',
            field=models.FloatField(default='', verbose_name='Tilt value'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='resolution_type',
            field=models.CharField(default='', max_length=30, verbose_name='Resolution Type'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='resolution_value',
            field=models.FloatField(default=0, verbose_name='Resolution [m]'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='swath',
            field=models.FloatField(default=0, verbose_name='Swath [km]'),
        ),
    ]
